import type { AbcChecklistItemDef } from './types';

/** Agentic Benchmark Checklist items (Zhu et al.) used by the dashboard. */
export const ABC_CHECKLIST: AbcChecklistItemDef[] = [
  {
    id: 'T.1',
    pillar: 'taskValidity',
    title: 'Tool versions specified',
    description: 'Self-hosted tools and package versions are pinned in the task setup.',
    requiresManual: true,
  },
  {
    id: 'T.2',
    pillar: 'taskValidity',
    title: 'API availability',
    description: 'API-based tools have availability and rate-limit handling.',
    requiresManual: true,
  },
  {
    id: 'T.3',
    pillar: 'taskValidity',
    title: 'API interruption detection',
    description: 'API interruptions are detected and terminate evaluation when needed.',
    requiresManual: true,
  },
  {
    id: 'T.4',
    pillar: 'taskValidity',
    title: 'Environment cleanup',
    description: 'Legacy state is cleaned between tasks (Clean Session / isolation).',
    requiresManual: false,
  },
  {
    id: 'T.5',
    pillar: 'taskValidity',
    title: 'Ground-truth isolation',
    description: 'Agents cannot peek at ground-truth results.',
    requiresManual: true,
  },
  {
    id: 'T.6',
    pillar: 'taskValidity',
    title: 'Reproducible environment',
    description: 'Environment and evaluator versions are frozen and reproducible.',
    requiresManual: false,
  },
  {
    id: 'T.7',
    pillar: 'taskValidity',
    title: 'Ground-truth annotation verified',
    description: 'Ground-truth annotations were manually verified.',
    requiresManual: true,
  },
  {
    id: 'T.8',
    pillar: 'taskValidity',
    title: 'Task setup verified',
    description: 'Task configuration was verified for correctness.',
    requiresManual: true,
  },
  {
    id: 'T.9',
    pillar: 'taskValidity',
    title: 'Oracle / solvability check',
    description: 'An oracle or pilot confirms tasks are solvable as intended.',
    requiresManual: true,
  },
  {
    id: 'T.10',
    pillar: 'taskValidity',
    title: 'Outlier inspection',
    description: 'Pilot outliers were inspected for shortcuts or impossible tasks.',
    requiresManual: true,
  },
  {
    id: 'O.a.1',
    pillar: 'outcomeValidity',
    title: 'String matching: equivalents',
    description: 'Whole-string matching accounts for semantically equivalent expressions.',
    requiresManual: true,
  },
  {
    id: 'O.a.2',
    pillar: 'outcomeValidity',
    title: 'String matching: redundancy',
    description: 'Whole-string matching accounts for redundant wording.',
    requiresManual: true,
  },
  {
    id: 'O.b.1',
    pillar: 'outcomeValidity',
    title: 'Substring: negation',
    description: 'Substring matching handles negation modifiers.',
    requiresManual: true,
  },
  {
    id: 'O.b.2',
    pillar: 'outcomeValidity',
    title: 'Substring: no list-all shortcut',
    description: 'Tasks prevent success by listing all possible answers.',
    requiresManual: true,
  },
  {
    id: 'O.b.3',
    pillar: 'outcomeValidity',
    title: 'Substring: no guessing',
    description: 'Tasks prevent success by guessing.',
    requiresManual: true,
  },
  {
    id: 'O.c.1',
    pillar: 'outcomeValidity',
    title: 'LLM-as-judge validated',
    description: 'LLM judge accuracy / consistency was assessed (e.g. multi-run Consistency).',
    requiresManual: false,
  },
  {
    id: 'O.d.1',
    pillar: 'outcomeValidity',
    title: 'Unit tests verified',
    description: 'Unit-test cases were manually verified when used as graders.',
    requiresManual: true,
  },
  {
    id: 'O.d.2',
    pillar: 'outcomeValidity',
    title: 'Unit-test quality metrics',
    description: 'Objective quality metrics (coverage, complexity) back unit tests.',
    requiresManual: true,
  },
  {
    id: 'O.e.1',
    pillar: 'outcomeValidity',
    title: 'Fuzz: input diversity',
    description: 'Fuzz testing covers diverse values, types, and layouts.',
    requiresManual: true,
  },
  {
    id: 'O.e.2',
    pillar: 'outcomeValidity',
    title: 'Fuzz: edge cases',
    description: 'Fuzz testing covers edge cases relevant to the program.',
    requiresManual: true,
  },
  {
    id: 'O.e.3',
    pillar: 'outcomeValidity',
    title: 'Fuzz: inputs affect outputs',
    description: 'Fuzz inputs actually affect program outputs.',
    requiresManual: true,
  },
  {
    id: 'O.f.1',
    pillar: 'outcomeValidity',
    title: 'E2E branch coverage',
    description: 'End-to-end tests cover workflow branches.',
    requiresManual: true,
  },
  {
    id: 'O.f.2',
    pillar: 'outcomeValidity',
    title: 'E2E determinism',
    description: 'End-to-end tests eliminate non-determinism for repeatability.',
    requiresManual: true,
  },
  {
    id: 'O.g.1',
    pillar: 'outcomeValidity',
    title: 'State matching completeness',
    description: 'Ground-truth states include all successful outcomes.',
    requiresManual: true,
  },
  {
    id: 'O.g.2',
    pillar: 'outcomeValidity',
    title: 'Relevant and irrelevant states',
    description: 'State space includes relevant and irrelevant states.',
    requiresManual: true,
  },
  {
    id: 'O.g.3',
    pillar: 'outcomeValidity',
    title: 'Complex state space',
    description: 'State space is complex enough to resist trivial success.',
    requiresManual: true,
  },
  {
    id: 'O.h.1',
    pillar: 'outcomeValidity',
    title: 'Answer parser assumptions',
    description: 'Parser format assumptions are explicit.',
    requiresManual: true,
  },
  {
    id: 'O.h.2',
    pillar: 'outcomeValidity',
    title: 'No guessable final answers',
    description: 'Tasks avoid success by guessing the final answer.',
    requiresManual: true,
  },
  {
    id: 'O.i.1',
    pillar: 'outcomeValidity',
    title: 'Quality metrics correlate with process',
    description: 'Process-based agentic metrics are used alongside outcome metrics.',
    requiresManual: false,
  },
  {
    id: 'R.1',
    pillar: 'benchmarkReporting',
    title: 'Dataset openness',
    description: 'Evaluation dataset (source Data Table) is attached and exportable.',
    requiresManual: false,
  },
  {
    id: 'R.2',
    pillar: 'benchmarkReporting',
    title: 'Harness openness',
    description: 'Evaluation harness (workflow + Aggregate sink) is exportable.',
    requiresManual: false,
  },
  {
    id: 'R.3',
    pillar: 'benchmarkReporting',
    title: 'Contamination prevention',
    description: 'Measures exist to prevent data contamination.',
    requiresManual: true,
  },
  {
    id: 'R.4',
    pillar: 'benchmarkReporting',
    title: 'Contamination disclosure',
    description: 'Contamination risks are disclosed.',
    requiresManual: true,
  },
  {
    id: 'R.5',
    pillar: 'benchmarkReporting',
    title: 'Capabilities specified',
    description: 'Target capabilities under evaluation are clearly specified.',
    requiresManual: true,
  },
  {
    id: 'R.6',
    pillar: 'benchmarkReporting',
    title: 'Construct validity',
    description: 'Construct validity of the benchmark is articulated.',
    requiresManual: true,
  },
  {
    id: 'R.7',
    pillar: 'benchmarkReporting',
    title: 'Mitigation documented',
    description: 'Validity limitations and mitigations are documented.',
    requiresManual: true,
  },
  {
    id: 'R.8',
    pillar: 'benchmarkReporting',
    title: 'Qualitative limitation evidence',
    description: 'Qualitative evidence of limitation impact is provided.',
    requiresManual: true,
  },
  {
    id: 'R.9',
    pillar: 'benchmarkReporting',
    title: 'Quantitative limitation evidence',
    description: 'Quantitative evidence of limitation impact is provided.',
    requiresManual: true,
  },
  {
    id: 'R.10',
    pillar: 'benchmarkReporting',
    title: 'Statistical significance',
    description: 'Multi-run Consistency stats (std/cv) support significance claims.',
    requiresManual: false,
  },
  {
    id: 'R.11',
    pillar: 'benchmarkReporting',
    title: 'Interpretation guidelines',
    description: 'Pass rules and thresholds guide result interpretation.',
    requiresManual: false,
  },
  {
    id: 'R.12',
    pillar: 'benchmarkReporting',
    title: 'Baseline comparisons',
    description: 'Appropriate baselines are compared.',
    requiresManual: true,
  },
  {
    id: 'R.13',
    pillar: 'benchmarkReporting',
    title: 'Baseline documentation',
    description: 'Baseline selection is documented.',
    requiresManual: true,
  },
];

export const PILLAR_TITLES = {
  taskValidity: 'Task Validity',
  outcomeValidity: 'Outcome Validity',
  benchmarkReporting: 'Benchmark Reporting',
} as const;
